# Generated by Django 2.1.7 on 2019-04-07 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkDocumentResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents')),
                ('description', models.TextField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('visibility', models.CharField(choices=[('PR', 'private'), ('PU', 'public')], default='public', max_length=20)),
                ('seriousness', models.CharField(choices=[('CA', 'Casual'), ('SE', 'Serious'), ('VS', 'Very Serious')], default='Very Serious', max_length=20)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(related_name='topics_subscribe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='linkdocumentresource',
            name='topic_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_documents', to='topic.Topic'),
        ),
    ]
